#  Prueba 1

In [4]:
from datetime import datetime
from scipy.optimize import curve_fit
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib inline

#Lectura de datos y filtrado para Colombia
url = 'http://cowid.netlify.com/data/full_data.csv'

datos = pd.read_csv(url)

datos = datos[datos['location'].isin(['Russia'])] #Filtro la Informacion solo para Ecuador
datos = datos.loc[:,['date','total_cases']] #Selecciono las columnas de analasis

# Expresar las fechas en numero de dias desde el 01 Enero
formato = '%Y-%m-%d'
fecha = datos['date']
datos['date'] = fecha.map(lambda x : (datetime.strptime(x, formato) - datetime.strptime("2020-01-01", formato)).days)

#Obtenci√≥n de los datos para las variables d√≠as y total_casos
dias = list(datos.iloc [:, 0])
total_casos = list(datos.iloc [:, 1])

#Obtenci√≥n del d√≠a objetivo
dia_objetivo = dias[-1] + 7

datos

      date  total_cases
2081    31            2
2082    32            2
2083    33            2
2084    34            2
2085    35            2
2086    36            2
2087    37            2
2088    38            2
2089    39            2
2090    40            2
2091    41            2
2092    42            2
2093    43            2
2094    44            2
2095    45            2
2096    46            2
2097    47            2
2098    48            2
2099    49            2
2100    50            2
2101    51            2
2102    52            2
2103    53            2
2104    54            2
2105    55            2
2106    56            2
2107    57            2
2108    58            2
2109    59            2
2110    60            2
2111    61            2
2112    62            3
2113    63            3
2114    64            3
2115    65            4
2116    66            7
2117    67            7
2118    68            7
2119    69            7
2120    70            7
2121    71           20
2122    72           34
2123    73           34
2124    74           34
2125    75           63
2126    76           93

In [ ]:
datos.plot(x ='date', y='total_cases')

### Lineal

In [ ]:
modelo_lineal = LinearRegression()
modelo_lineal.fit(np.array(dias).reshape(-1, 1), total_casos)

prediccion_semana = modelo_lineal.predict([[dia_objetivo]])
print('Predicci√≥n:', int(prediccion_semana))

rango_dias = np.arange(60, 85, 1)

plt.scatter(dias, total_casos , color = 'red')
plt.plot(rango_dias, modelo_lineal.predict(rango_dias.reshape(-1, 1)), color = 'green')
plt.show()

### Logistico

In [ ]:
modelo_logistico = lambda x, a, b: a + b * np.log(x)

ajuste = curve_fit(modelo_logistico, dias, total_casos)

rango_dias = np.arange(60, 85, 1)

prediccion_total = [modelo_logistico(i, ajuste[0][0], ajuste[0][1]) for i in rango_dias]

prediccion_semana = prediccion_total[-3]
print('Predicci√≥n: ', int(prediccion_semana))

plt.scatter(dias, total_casos , color = 'red')
plt.plot(rango_dias, prediccion_total, color = 'green')
plt.show()

### Exponencial

### Polinomial

In [ ]:
definicion = PolynomialFeatures(degree = 5)
modelo_polinomial = LinearRegression()

Dias = definicion.fit_transform(np.array(dias).reshape(-1, 1))

modelo_polinomial.fit(Dias, total_casos)

prediccion_semana = modelo_polinomial.predict([Dias[-1] + 7])
print('Predicci√≥n: ', int(prediccion_semana))

rango_dias = np.array(range(60, 85))
rango_dias = definicion.fit_transform(rango_dias.reshape(-1, 1))

plt.scatter(dias, total_casos, color = 'red')
plt.plot(modelo_polinomial.predict(rango_dias), color = 'green')
plt.show()

### Probabil√≠stico

In [ ]:
mediana = datos['total_cases'].median()

modelo_probabilistico = lambda y: int(y[-1] + mediana)

prediccion = total_casos

for i in range(dias[-1], dia_objetivo):
    dias.append(i)
    prediccion.append(modelo_probabilistico(prediccion))
    
prediccion_semana = modelo_probabilistico(total_casos)
print('Predicci√≥n: ', int(prediccion_semana))

plt.scatter(dias, total_casos, color = 'red')
plt.plot(dias, total_casos, color = 'green')
plt.show()